/** @type {import('next').NextConfig} */
const BACKEND_URL = (process.env.BACKEND_URL || "").replace(/\/+$/, "");

const nextConfig = {
  reactStrictMode: true,
  // Lets a production build run in its own folder while `next dev` keeps using .next
  distDir: process.env.NEXT_DIST_DIR || ".next",
  /**
   * In production the browser talks only to this site: /api/* is passed on to the backend.
   * The login cookie is then first-party, so phones (Safari) keep it. Set BACKEND_URL on the host,
   * and leave NEXT_PUBLIC_API_URL empty there.
   */
  async rewrites() {
    if (!BACKEND_URL) return [];
    return { beforeFiles: [{ source: "/api/:path*", destination: `${BACKEND_URL}/api/:path*` }] };
  },
  async redirects() {
    // Old URLs from before the Phase 0 restructure (29 Sep 2026) keep working.
    return [
      { source: "/dashboard/admin", destination: "/dashboard", permanent: false },
      { source: "/collect-fees", destination: "/fees/collect", permanent: false },
      { source: "/search-student", destination: "/students", permanent: false },
      { source: "/search-student-advance", destination: "/students", permanent: false },
      { source: "/list-students", destination: "/students", permanent: false },
      { source: "/list-students-beta", destination: "/students", permanent: false },
      { source: "/students/list", destination: "/students", permanent: false },
      { source: "/students/filter", destination: "/students", permanent: false },
      { source: "/new-admissions", destination: "/students", permanent: false },
      { source: "/removed-students", destination: "/students", permanent: false },
      { source: "/list-siblings", destination: "/students", permanent: false },
      { source: "/students/new", destination: "/students?new=1", permanent: false },
      { source: "/students/add", destination: "/students?new=1", permanent: false },
      { source: "/add-students", destination: "/students?new=1", permanent: false },
      { source: "/search-enquiry", destination: "/students/enquiries", permanent: false },
      { source: "/list-offline-admission-test", destination: "/students/enquiries", permanent: false },
      { source: "/admission-test-results", destination: "/students/enquiries", permanent: false },
      { source: "/promote-students", destination: "/students/promote", permanent: false },
      { source: "/students/move", destination: "/students/promote", permanent: false },
      { source: "/move-students", destination: "/students/promote", permanent: false },
      { source: "/studying-certificate-history", destination: "/students/certificates", permanent: false },
      { source: "/students/bulk-certificates", destination: "/students/certificates", permanent: false },
      { source: "/bulk-certificate", destination: "/students/certificates", permanent: false },
      { source: "/reports/tc-history", destination: "/students/certificates", permanent: false },
      { source: "/reports/certificates-history", destination: "/students/certificates", permanent: false },
      { source: "/student-documents", destination: "/students/documents", permanent: false },
      { source: "/students/photo-upload", destination: "/students/documents", permanent: false },
      { source: "/upload-student-pics", destination: "/students/documents", permanent: false },
      { source: "/verification-list", destination: "/students/documents", permanent: false },
      { source: "/students/bulk-print", destination: "/students/print", permanent: false },
      { source: "/bulk-print", destination: "/students/print", permanent: false },
      { source: "/students/houses", destination: "/settings", permanent: false },
      { source: "/students/serial-generator", destination: "/settings", permanent: false },
      { source: "/student-profile-settings", destination: "/settings", permanent: false },
      { source: "/attendance/student/mark", destination: "/attendance/mark", permanent: false },
      { source: "/mark-attendance", destination: "/attendance/mark", permanent: false },
      { source: "/attendance/student/daily-report", destination: "/attendance/today", permanent: false },
      { source: "/daily-attendance-report", destination: "/attendance/today", permanent: false },
      { source: "/daily-section-attendance-report", destination: "/attendance/today", permanent: false },
      { source: "/attendance/student/section-report", destination: "/attendance/register", permanent: false },
      { source: "/reports/attendance", destination: "/attendance/register", permanent: false },
      { source: "/attendance/student/slots", destination: "/settings", permanent: false },
      { source: "/attendance-slots", destination: "/settings", permanent: false },
      { source: "/attendance/staff/slots", destination: "/settings", permanent: false },
      { source: "/staff-attendance-slots", destination: "/settings", permanent: false },
      { source: "/attendance/staff/mark", destination: "/staff/attendance", permanent: false },
      { source: "/attendance/staff/daily-report", destination: "/staff/attendance", permanent: false },
      { source: "/mark-staff-attendance", destination: "/staff/attendance", permanent: false },
      { source: "/daily-staff-attendance", destination: "/staff/attendance", permanent: false },
      { source: "/biometric", destination: "/staff/attendance", permanent: false },
      { source: "/send-notifications", destination: "/messages/new", permanent: false },
      { source: "/send-circular-school", destination: "/messages/new", permanent: false },
      { source: "/send-circular-classes", destination: "/messages/new", permanent: false },
      { source: "/academic/circulars", destination: "/messages/new", permanent: false },
      { source: "/circular-history", destination: "/messages", permanent: false },
      { source: "/daily-sms-count", destination: "/messages", permanent: false },
      { source: "/event-holidays", destination: "/calendar", permanent: false },
      { source: "/academic/calendar", destination: "/calendar", permanent: false },
      { source: "/list-birthday", destination: "/birthdays", permanent: false },
      { source: "/academic/birthdays", destination: "/birthdays", permanent: false },
      { source: "/list-terms", destination: "/exams/setup", permanent: false },
      { source: "/add-exam", destination: "/exams/setup", permanent: false },
      { source: "/exam-schedule", destination: "/exams/setup", permanent: false },
      { source: "/grade-setting", destination: "/exams/setup", permanent: false },
      { source: "/coscholastic-skills", destination: "/exams/setup", permanent: false },
      { source: "/report-card-keys", destination: "/exams/setup", permanent: false },
      { source: "/exams/add", destination: "/exams/setup", permanent: false },
      { source: "/exams/grade-settings", destination: "/exams/setup", permanent: false },
      { source: "/exams/schedule", destination: "/exams/setup", permanent: false },
      { source: "/exams/terms", destination: "/exams/setup", permanent: false },
      { source: "/view-result", destination: "/exams/marks", permanent: false },
      { source: "/coscholastic-grades", destination: "/exams/marks", permanent: false },
      { source: "/exams/results", destination: "/exams/marks", permanent: false },
      { source: "/exams/class-tests", destination: "/exams/marks", permanent: false },
      { source: "/exams/co-scholastic", destination: "/exams/marks", permanent: false },
      { source: "/report-card", destination: "/exams/report-cards", permanent: false },
      { source: "/icse-report-card", destination: "/exams/report-cards", permanent: false },
      { source: "/class-test-report-card", destination: "/exams/report-cards", permanent: false },
      { source: "/add-timetable", destination: "/academics/timetable", permanent: false },
      { source: "/timetablefile", destination: "/academics/timetable", permanent: false },
      { source: "/academic/timetable", destination: "/academics/timetable", permanent: false },
      { source: "/homework", destination: "/academics/homework", permanent: false },
      { source: "/show-homework", destination: "/academics/homework", permanent: false },
      { source: "/homework/add", destination: "/academics/homework", permanent: false },
      { source: "/homework/view", destination: "/academics/homework", permanent: false },
      { source: "/syllabus-overview", destination: "/academics/syllabus", permanent: false },
      { source: "/syllabus-progress", destination: "/academics/syllabus", permanent: false },
      { source: "/syllabus-file", destination: "/academics/syllabus", permanent: false },
      { source: "/list-syllabus-chapters-template", destination: "/academics/syllabus", permanent: false },
      { source: "/institute/syllabus-templates", destination: "/academics/syllabus", permanent: false },
      { source: "/add-copy-check", destination: "/academics/copy-check", permanent: false },
      { source: "/copy-check", destination: "/academics/copy-check", permanent: false },
      { source: "/copy-check-remark-type", destination: "/academics/copy-check", permanent: false },
      { source: "/academic/copy-check", destination: "/academics/copy-check", permanent: false },
      { source: "/staff/search", destination: "/staff", permanent: false },
      { source: "/staffs", destination: "/staff", permanent: false },
      { source: "/all-staff", destination: "/staff", permanent: false },
      { source: "/search-staff", destination: "/staff", permanent: false },
      { source: "/staff/list", destination: "/staff", permanent: false },
      { source: "/staff/left-staff", destination: "/staff", permanent: false },
      { source: "/left-staff", destination: "/staff", permanent: false },
      { source: "/staff/add", destination: "/staff/new", permanent: false },
      { source: "/add-staff", destination: "/staff/new", permanent: false },
      { source: "/staff/departments", destination: "/staff/allocation", permanent: false },
      { source: "/pending-leaves", destination: "/staff/leave", permanent: false },
      { source: "/approved-leaves", destination: "/staff/leave", permanent: false },
      { source: "/academic/leave-applications", destination: "/staff/leave", permanent: false },
      { source: "/staff/profile-settings", destination: "/settings/users", permanent: false },
      { source: "/staff-profile-settings", destination: "/settings/users", permanent: false },
      { source: "/classes-subjects", destination: "/settings/classes", permanent: false },
      { source: "/institute/classes-subjects", destination: "/settings/classes", permanent: false },
      { source: "/school-details", destination: "/settings", permanent: false },
      { source: "/institute/basic-details", destination: "/settings", permanent: false },
      { source: "/school-settings", destination: "/settings", permanent: false },
      { source: "/institute/custom-settings", destination: "/settings", permanent: false },
      { source: "/active-sessions", destination: "/settings", permanent: false },
      { source: "/institute/active-sessions", destination: "/settings", permanent: false },
      { source: "/design/templates", destination: "/settings/templates", permanent: false },
      { source: "/reports/gate-pass-history", destination: "/reports", permanent: false },
      { source: "/reports/siblings", destination: "/reports", permanent: false },
      { source: "/reports/teacher-performance", destination: "/reports", permanent: false },
      { source: "/teacher-performance", destination: "/reports", permanent: false },
      { source: "/assign-mentor", destination: "/dashboard", permanent: false },
      { source: "/mentees", destination: "/dashboard", permanent: false },
      { source: "/teacher-request", destination: "/dashboard", permanent: false },
      { source: "/gallery", destination: "/dashboard", permanent: false },
    ];
  },
};

export default nextConfig;
